name: Publish to GitHub

on: 
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        runs-on: macos-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup xmake
              uses: xmake-io/github-action-setup-xmake@v1
              with:
                xmake-version: latest

            - name: Setup Homebrew
              run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

            - name: Setup LLVM
              run: |
                brew install llvm
                export PATH="/opt/homebrew/opt/llvm/bin:$PATH"

            - name: Build
              run: |
                xmake f -p macosx -a arm64 -m release
                xmake -y

            - name: Upload Artifacts
              uses: actions/upload-artifact@v4
              with:
                name: Mamba
                path: |
                    build/macosx/arm64/release/Jvav
                    build/windows/x64/release/Jvav.exe
